def arg_err(error):
    print(error)